version: '3.8'

services:
  traccar:
    image: traccar/traccar:latest
    hostname: traccar
    restart: unless-stopped
    ports:
      - "8082:8082" # Porta da interface web (interna do container)
      - "5000-5150:5000-5150/tcp" # Portas para protocolos de rastreadores (TCP)
      - "5000-5150:5000-5150/udp" # Portas para protocolos de rastreadores (UDP)
    volumes:
      - traccar_logs:/opt/traccar/logs
      - traccar_data:/opt/traccar/data
    environment:
      # Configuração do Banco de Dados PostgreSQL - Use o nome do serviço do Coolify e a porta interna (5432)
      - TRACCAR_DATABASE_DRIVER=org.postgresql.Driver
      - TRACCAR_DATABASE_URL=jdbc:postgresql://postgresql-traccar:5432/postgres
      - TRACCAR_DATABASE_USER=postgres
      - TRACCAR_DATABASE_PASSWORD=jxyJ5aRTO5NvyL6O8HAEopNemVd5rKjYwizJAygtZLlkuK5gi26Maqx1U3MemKCB
      - JVM_OPTIONS=-Xms1g -Xmx1g -Djava.net.preferIPv4Stack=true # Ajuste a memória conforme a necessidade da sua VPS
    # Caso precise de um Dockerfile para build customizado (opcional)
    # build: .

volumes:
  traccar_logs:
  traccar_data:
