# Dockerfile

FROM traccar/traccar:latest

# Copia o seu traccar.xml personalizado para o local correto dentro da imagem
COPY traccar-config/traccar.xml /opt/traccar/conf/traccar.xml

# Cria diretórios para logs e dados (se não existirem, ou para garantir permissões)
# A imagem oficial já lida com /opt/traccar/data, mas garantir o de logs é bom.
RUN mkdir -p /opt/traccar/logs \
    && chmod 777 /opt/traccar/logs # Garante permissões de escrita para o Traccar